### PR TITLE
migrate latino parties from Party Facts web

### PR DESCRIPTION
**Pull request by pbederke**

### CODE REVIEW

**Comment by hdigital** [comment]
@pbederke I wonder if we should remove duplicate party names

**Comment by pbederke** [comment]
Duplicate party names only appear if there are different party IDs. So I would keep them.

**Comment by hdigital** [comment]
I prefer avoiding duplicates but it don't seem to be too many here. You know the data, it don't seem to be too many duplicates her, so fine with me.

**Comment by hdigital** [comment]
@pbederke did a final check of the code and used styler to reformat code. All fine with me now and ready to merge and move public at PF-Web now.

**Pull request merged**
